services:
  bot:
    image: bot
    container_name: Afonya
    build:
      context: .
      dockerfile: src/Afonya.Bot.WebWorker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - data:/app/db:rw

volumes:
  data:
