FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

RUN apt-get update && apt-get install -y libfontconfig1

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["src/Services/Bot/Afonya.Bot.WebWorker/Afonya.Bot.WebWorker.csproj", "src/Services/Bot/Afonya.Bot.WebWorker/"]
RUN dotnet restore "src/Services/Bot/Afonya.Bot.WebWorker/Afonya.Bot.WebWorker.csproj"
COPY . .
WORKDIR "/src/src/Services/Bot/Afonya.Bot.WebWorker"
RUN dotnet build "Afonya.Bot.WebWorker.csproj" -c $configuration -o /app/build

FROM build AS publish
RUN dotnet publish "Afonya.Bot.WebWorker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
USER root
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Afonya.Bot.WebWorker.dll"]