version: '3.4'

networks:
  app:
    driver: "bridge"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    hostname: "nginx"
    volumes:
      - ../deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../deploy/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ../deploy/ssl/local.crt:/etc/ssl/certs/local.crt:ro
      - ../deploy/ssl/local.key:/etc/ssl/certs/local.key:ro
      - ../deploy/nginx/conf.d/default_local.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      app:
    depends_on:
      - bot

  bot:
    container_name: bot
    hostname: bot
    image: ${DOCKER_REGISTRY-}bot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Services/Bot/Dockerfile
    networks:
      app: